spring:
  profiles:
    active: local
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        show_sql: true
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
server:
  port: 8000
---
spring:
  config:
    activate:
      on-profile: mem
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:musinsa
    username: sa
    password:
aggregator:
  server: localhost:8002
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost:1521/musinsa
    username: sa
    password:
aggregator:
  server: localhost:8002
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://musinsa-h2:1521/musinsa
    username: sa
    password:
aggregator:
  server: aggregator:8002